### ISSUE TITLE
ACTIVE ADMIN section click on products NameError in Admin::Products#index 

### ISSUE THREAD

**Issue by skylarktechteam** [elygreenberg/NobleRails#10]
Latest Error - in the back end active admin section per book. SELECTING PRODUCTS.

NameError in Admin::Products#index 

- where is this even ... views/active_admin/resource/index.html.arb??

Showing /Users/johnmunnelly/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/bundler/gems/active_admin-9005b67e6f2a/app/views/active_admin/resource/index.html.arb where line #2 raised: 

uninitialized constant Product::Order
-----
Extracted source (around line #2)
 1 insert_tag renderer_for(:index)

**Comment by skylarktechteam** [comment]
This was fix 

`default_actions` is no longer provided in ActiveAdmin 1.x. Use `actions` instead.

so I replaced in the ActiveAdmin folder /file
product.rb 
replace `default_actions` with `actions` instead.
-----
index do
    selectable_column
    column :image do |product|
      image_tag product.image.url(:thumb)
    end
    column :title
    column :sku
    column :price
    column :created_at
    column :updated_at
    # removed default_actions replaced with actions as runtime error attempted fix worked 
    actions


index do
    selectable_column
    column :image do |product|
      image_tag product.image.url(:thumb)
    end
    column :title
    column :sku
    column :price
    column :created_at
    column :updated_at
#not this 
    default_actions 
  end

**Comment by elygreenberg** [comment]
Glad you were able to get this fixed.
