### ISSUE TITLE
Do we need to create some connection device script in Postgres

### ISSUE THREAD

**Issue by skylarktechteam** [elygreenberg/NobleRails#13]
Hi Ely 

I have tried two installs of Pstgres one with brew install then uninstalled that and switched to install from Enterprise db but same error on the 2nd PG install type.

I am getting an error -- I have a new mac so I did need to set up apache server on it and Im getting a local host "It works" on the apache server localhost.

this is the error I am getting - have you seen this error or have any ideas I can try

could not connect to server: No such file or directory 
Is the server running locally and accepting connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"? 

and following

Extracted source (around line #655):

653
654
655
656
657
658
              

	

        # connected server's characteristics.
        def connect
          @connection = PGconn.connect(@connection_parameters)

          # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below, and as of
          # PostgreSQL 8.3 it has a fixed precision of 19. PostgreSQLColumn.extract_precision

Rails.root: /Users/johnmunnelly/Documents/files/rubyrails/rodent/rodentreport
Application Trace | Framework Trace | Full Trace

activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize'
activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'

etc etc for a hundred or so lines

Happy Thanksgiving from PostGres ;)

**Comment by DiGsInNY** [comment]
Hi Ely,

I'm having this sam problem.

Thanks,
Michelle

On Sun, Nov 29, 2015 at 9:06 PM, skylarktechteam <notifications@github.com>
wrote:

> Hi Ely
>
> I have tried two installs of Pstgres one with brew install then
> uninstalled that and switched to install from Enterprise db but same error
> on the 2nd PG install type.
>
> I am getting an error -- I have a new mac so I did need to set up apache
> server on it and Im getting a local host "It works" on the apache server
> localhost.
>
> this is the error I am getting - have you seen this error or have any
> ideas I can try
>
> could not connect to server: No such file or directory
> Is the server running locally and accepting connections on Unix domain
> socket "/var/pgsql_socket/.s.PGSQL.5432"?
>
> and following
>
> Extracted source (around line #655):
>
> 653
> 654
> 655
> 656
> 657
> 658
>
>     # connected server's characteristics.
>     def connect
>       @connection = PGconn.connect(@connection_parameters)
>
>       # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below, and as of
>       # PostgreSQL 8.3 it has a fixed precision of 19. PostgreSQLColumn.extract_precision
>
> Rails.root:
> /Users/johnmunnelly/Documents/files/rubyrails/rodent/rodentreport
> Application Trace | Framework Trace | Full Trace
>
> activerecord (4.2.4)
> lib/active_record/connection_adapters/postgresql_adapter.rb:655:in
> initialize'
> activerecord (4.2.4)
> lib/active_record/connection_adapters/postgresql_adapter.rb:655:innew'
> activerecord (4.2.4)
> lib/active_record/connection_adapters/postgresql_adapter.rb:655:in
> connect'
> activerecord (4.2.4)
> lib/active_record/connection_adapters/postgresql_adapter.rb:242:in
> initialize'
> activerecord (4.2.4)
> lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
>
> etc etc for a hundred or so lines
>
> Happy Thanksgiving from PostGres ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elygreenberg/NobleRails/issues/13>.
>



-- 
~Michelle

**Comment by DiGsInNY** [comment]
...as well as this error and I also don't have schema.rb which I'm assuming
would download in the migration?

Michelles-MacBook-Pro:rodentreport DigsInNY$ rake db:migrate

[Simple Form] Simple Form is not configured in the application and will use
the default values. Use `rails generate simple_form:install` to generate
the Simple Form configuration.

rake aborted!

PG::ConnectionBad: could not connect to server: No such file or directory

Is the server running locally and accepting

connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


Tasks: TOP => db:migrate

(See full trace by running task with --trace)


Thanks,

Michelle

On Sun, Dec 6, 2015 at 11:48 PM, Michelle DiGaetano <med329@gmail.com>
wrote:

> Hi Ely,
>
> I'm having this sam problem.
>
> Thanks,
> Michelle
>
> On Sun, Nov 29, 2015 at 9:06 PM, skylarktechteam <notifications@github.com
> > wrote:
>
>> Hi Ely
>>
>> I have tried two installs of Pstgres one with brew install then
>> uninstalled that and switched to install from Enterprise db but same error
>> on the 2nd PG install type.
>>
>> I am getting an error -- I have a new mac so I did need to set up apache
>> server on it and Im getting a local host "It works" on the apache server
>> localhost.
>>
>> this is the error I am getting - have you seen this error or have any
>> ideas I can try
>>
>> could not connect to server: No such file or directory
>> Is the server running locally and accepting connections on Unix domain
>> socket "/var/pgsql_socket/.s.PGSQL.5432"?
>>
>> and following
>>
>> Extracted source (around line #655):
>>
>> 653
>> 654
>> 655
>> 656
>> 657
>> 658
>>
>>     # connected server's characteristics.
>>     def connect
>>       @connection = PGconn.connect(@connection_parameters)
>>
>>       # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below, and as of
>>       # PostgreSQL 8.3 it has a fixed precision of 19. PostgreSQLColumn.extract_precision
>>
>> Rails.root:
>> /Users/johnmunnelly/Documents/files/rubyrails/rodent/rodentreport
>> Application Trace | Framework Trace | Full Trace
>>
>> activerecord (4.2.4)
>> lib/active_record/connection_adapters/postgresql_adapter.rb:655:in
>> initialize'
>> activerecord (4.2.4)
>> lib/active_record/connection_adapters/postgresql_adapter.rb:655:innew'
>> activerecord (4.2.4)
>> lib/active_record/connection_adapters/postgresql_adapter.rb:655:in
>> connect'
>> activerecord (4.2.4)
>> lib/active_record/connection_adapters/postgresql_adapter.rb:242:in
>> initialize'
>> activerecord (4.2.4)
>> lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
>>
>> etc etc for a hundred or so lines
>>
>> Happy Thanksgiving from PostGres ;)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elygreenberg/NobleRails/issues/13>.
>>
>
>
>
> --
> ~Michelle
>



-- 
~Michelle

**Comment by elygreenberg** [comment]
It looks like the error is from Postgres not starting automatically. Use
this command on the command line to startup postgres.

pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log
start

**Comment by DiGsInNY** [comment]
Ok, I'll try. I also got stuck on #18 1A
rodentreport-reports_controller.rb doesn't exist and I can't continue.

Will running the Postgres command de story what I was able to to up to #18?

Thanks,
Michelle

On Monday, December 7, 2015, elygreenberg <notifications@github.com> wrote:

> It looks like the error is from Postgres not starting automatically. Use
> this command on the command line to startup postgres.
>
> pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log
> start
>
> On Mon, Dec 7, 2015 at 12:28 AM, Michelle DiGaetano <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > ...as well as this error and I also don't have schema.rb which I'm
> assuming
> > would download in the migration?
> >
> > Michelles-MacBook-Pro:rodentreport DigsInNY$ rake db:migrate
> >
> > [Simple Form] Simple Form is not configured in the application and will
> use
> > the default values. Use `rails generate simple_form:install` to generate
> > the Simple Form configuration.
> >
> > rake aborted!
> >
> > PG::ConnectionBad: could not connect to server: No such file or directory
> >
> > Is the server running locally and accepting
> >
> > connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
> >
> >
> > Tasks: TOP => db:migrate
> >
> > (See full trace by running task with --trace)
> >
> >
> > Thanks,
> >
> > Michelle
> >
> > On Sun, Dec 6, 2015 at 11:48 PM, Michelle DiGaetano <med329@gmail.com
> <javascript:_e(%7B%7D,'cvml','med329@gmail.com');>>
> > wrote:
> >
> > > Hi Ely,
> > >
> > > I'm having this sam problem.
> > >
> > > Thanks,
> > > Michelle
> > >
> > > On Sun, Nov 29, 2015 at 9:06 PM, skylarktechteam <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > wrote:
> > >
> > >> Hi Ely
> > >>
> > >> I have tried two installs of Pstgres one with brew install then
> > >> uninstalled that and switched to install from Enterprise db but same
> > error
> > >> on the 2nd PG install type.
> > >>
> > >> I am getting an error -- I have a new mac so I did need to set up
> apache
> > >> server on it and Im getting a local host "It works" on the apache
> server
> > >> localhost.
> > >>
> > >> this is the error I am getting - have you seen this error or have any
> > >> ideas I can try
> > >>
> > >> could not connect to server: No such file or directory
> > >> Is the server running locally and accepting connections on Unix domain
> > >> socket "/var/pgsql_socket/.s.PGSQL.5432"?
> > >>
> > >> and following
> > >>
> > >> Extracted source (around line #655):
> > >>
> > >> 653
> > >> 654
> > >> 655
> > >> 656
> > >> 657
> > >> 658
> > >>
> > >> # connected server's characteristics.
> > >> def connect
> > >> @connection = PGconn.connect(@connection_parameters)
> > >>
> > >> # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below,
> > and as of
> > >> # PostgreSQL 8.3 it has a fixed precision of 19.
> > PostgreSQLColumn.extract_precision
> > >>
> > >> Rails.root:
> > >> /Users/johnmunnelly/Documents/files/rubyrails/rodent/rodentreport
> > >> Application Trace | Framework Trace | Full Trace
> > >>
> > >> activerecord (4.2.4)
> > >> lib/active_record/connection_adapters/postgresql_adapter.rb:655:in
> > >> initialize'
> > >> activerecord (4.2.4)
> > >> lib/active_record/connection_adapters/postgresql_adapter.rb:655:innew'
> > >> activerecord (4.2.4)
> > >> lib/active_record/connection_adapters/postgresql_adapter.rb:655:in
> > >> connect'
> > >> activerecord (4.2.4)
> > >> lib/active_record/connection_adapters/postgresql_adapter.rb:242:in
> > >> initialize'
> > >> activerecord (4.2.4)
> > >> lib/active_record/connection_adapters/postgresql_adapter.rb:44:in
> `new'
> > >>
> > >> etc etc for a hundred or so lines
> > >>
> > >> Happy Thanksgiving from PostGres ;)
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/elygreenberg/NobleRails/issues/13>.
> > >>
> > >
> > >
> > >
> > > --
> > > ~Michelle
> > >
> >
> >
> >
> > --
> > ~Michelle
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elygreenberg/NobleRails/issues/13#issuecomment-162415514
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elygreenberg/NobleRails/issues/13#issuecomment-162560759>
> .
>


-- 
~Michelle
