### ISSUE TITLE
Rodentreport API Routes -namespace heading

### ISSUE THREAD

**Issue by skylarktechteam** [elygreenberg/NobleRails#16]
HI Ely
Im finishing up the json API Routes

Does pages 51 API Routes need lower case or commenting out in routes.rb - like as follows - 

resources :reports

 # api routes
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :buildings
    end
  end

**Comment by ergprocess** [comment]
Yes. A pound sign is missing. It's should be #api routes

**Comment by skylarktechteam** [comment]
Thanks - I put the # in to read

#api routes
