### ISSUE TITLE
Can't make class tonight - Wed 10/21

### ISSUE THREAD

**Issue by reneeylewis** [elygreenberg/NobleRails#4]
Hi Ely,
I'm sick and can't make it to class tonight. I've completed section 4D from textbook and section 6-Adding a Second Model to Blog application from http://guides.rubyonrails.org/getting_started.html.  Is there anything else I need to complete for tonight's lesson.

Renee

**Comment by elygreenberg** [comment]
Hi Renee,

Sorry your not feeling well. We'll be doing section 5 tonight of the flix
app. Please finish the blog tutorial for homework.

See you on Monday.
